spring:
  application.name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          url-expression: "'http://'+serviceId"
      x-forwarded:
        prefixEnabled: true
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.loadbalancer: TRACE
server.port: 8080
management:
  endpoints:
    web:
      exposure:
        include: '*'