spring:
  application.name: gateway
  cloud:
    gateway:
      x-forwarded:
        enabled: true
      discovery:
        locator:
          enabled: true
          url-expression: "'http://'+serviceId"

server.port: 8080
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.loadbalancer: TRACE
management:
  endpoints:
    web:
      exposure:
        include: '*'