spring:
  application.name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          url-expression: "'http://'+serviceId"

server.port: 8080
management:
  endpoints:
    web:
      exposure:
        include: '*'